# Generated by Django 4.1.7 on 2023-07-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_utilisateur_statut_alter_utilisateur_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="Images/Photos/utilisateurs",
                verbose_name="photo de profil",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("GESTIONNAIRE", "Gestionnaire"),
                    ("ENSEIGNANT", "Enseignant"),
                    ("ETUDIANT", "Etudiant"),
                    ("ADMINISTRATEUR", "Administrateur"),
                    ("ADMINISTRATEURSUPER", "Administrateur Super"),
                    ("DIRECTION", "Direction Institution"),
                    ("ACADEMIQUE", "Direction Academique"),
                ],
                max_length=30,
                verbose_name="rôle",
            ),
        ),
    ]
