# Generated by Django 4.1.7 on 2023-03-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrations", "0002_ecoles_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecoles",
            name="image",
            field=models.ImageField(
                null=True, upload_to="administrations/templates/pages/images/"
            ),
        ),
    ]
