# Generated by Django 4.1.7 on 2023-03-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrations", "0003_alter_ecoles_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="salles",
            name="Etablissement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.ecoles",
            ),
        ),
    ]
