# Generated by Django 4.1.7 on 2023-03-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrations", "0004_salles_etablissement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salles",
            name="Etablissement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="administrations.ecoles"
            ),
        ),
    ]
