# Generated by Django 4.1.7 on 2023-03-23 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrations", "0006_anneescolaires"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statutannees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Statutannee", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(model_name="enseignants", name="Matiere",),
        migrations.AddField(
            model_name="etudiants",
            name="Matricule",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="matieres",
            name="Professeur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.enseignants",
            ),
        ),
        migrations.AddField(
            model_name="matieres",
            name="Salle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.salles",
            ),
        ),
        migrations.AddField(
            model_name="salles",
            name="Anneescolaire",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="salles",
            name="Professeurprincipal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.enseignants",
            ),
        ),
        migrations.AlterField(
            model_name="enseignants",
            name="Matricule",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Note",
                    models.DecimalField(decimal_places=2, max_digits=4, null=True),
                ),
                (
                    "Cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.matieres",
                    ),
                ),
                (
                    "Etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.etudiants",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="anneescolaires",
            name="Statutannee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.statutannees",
            ),
        ),
    ]
