# Generated by Django 4.1.7 on 2023-03-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrations", "0007_statutannees_remove_enseignants_matiere_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enseignants",
            name="Matricule",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Moyennes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Moyenne",
                    models.DecimalField(decimal_places=2, max_digits=4, null=True),
                ),
                ("Rang", models.CharField(max_length=15, null=True)),
                (
                    "Etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.etudiants",
                    ),
                ),
            ],
        ),
    ]
