# Generated by Django 4.1.7 on 2023-03-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrations", "0008_alter_enseignants_matricule_moyennes"),
    ]

    operations = [
        migrations.RenameModel(old_name="Note", new_name="Notes",),
    ]
