# Generated by Django 4.1.7 on 2023-03-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrations", "0010_decoupages_moyennes_anneescolaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salles",
            name="Anneescolaire",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.anneescolaires",
            ),
        ),
    ]
