# Generated by Django 4.1.7 on 2023-03-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrations", "0011_alter_salles_anneescolaire"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statutdecoups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Statutdecoup", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="decoupages",
            name="Statutdecoup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.statutdecoups",
            ),
        ),
    ]
