# Generated by Django 4.1.7 on 2023-03-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrations", "0013_notes_salle"),
    ]

    operations = [
        migrations.AddField(
            model_name="moyennes",
            name="Total",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="notes",
            name="Appreciation",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notes",
            name="Professeur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.enseignants",
            ),
        ),
        migrations.AddField(
            model_name="notes",
            name="Typematiere",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.typematieres",
            ),
        ),
    ]
