# Generated by Django 4.1.7 on 2023-03-27 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "administrations",
            "0014_moyennes_total_notes_appreciation_notes_professeur_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiants",
            name="User",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
