# Generated by Django 4.1.7 on 2023-03-27 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("administrations", "0016_alter_etudiants_matricule"),
    ]

    operations = [
        migrations.AddField(
            model_name="enseignants",
            name="User",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="enseignants",
            name="Matricule",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="enseignants",
            name="Photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="Images/Photos/enseignants"
            ),
        ),
        migrations.AlterField(
            model_name="etudiants",
            name="Photo",
            field=models.ImageField(null=True, upload_to="Images/Photos/etudiants"),
        ),
    ]
