# Generated by Django 4.1.7 on 2023-03-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrations", "0018_alter_ecoles_image_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="salles", name="Effectif", field=models.IntegerField(null=True),
        ),
    ]
