# Generated by Django 4.1.7 on 2023-04-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrations", "0019_salles_effectif"),
    ]

    operations = [
        migrations.AddField(
            model_name="salles",
            name="Planning",
            field=models.ImageField(
                blank=True, null=True, upload_to="Images/Photos/salles"
            ),
        ),
    ]
