# Generated by Django 4.1.7 on 2023-06-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0020_salles_planning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moyennes",
            name="Total",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
