# Generated by Django 4.1.7 on 2023-06-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0023_alter_ecoles_etablissement"),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierScolaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Heuresabsence", models.IntegerField(default=0)),
                (
                    "Anneescolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.anneescolaires",
                    ),
                ),
                (
                    "Etudiant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.etudiants",
                    ),
                ),
            ],
        ),
    ]
