# Generated by Django 4.1.7 on 2023-06-15 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0024_dossierscolaire"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DossierScolaire",
            new_name="DossierScolaires",
        ),
        migrations.CreateModel(
            name="Catalogues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nom", models.CharField(max_length=250)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "Niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.niveaux",
                    ),
                ),
            ],
        ),
    ]
