# Generated by Django 4.1.7 on 2023-06-15 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0025_rename_dossierscolaire_dossierscolaires_catalogues"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catalogues",
            old_name="prix",
            new_name="Prix",
        ),
    ]
