# Generated by Django 4.1.7 on 2023-06-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "administrations",
            "0027_rename_heuresabsence_dossierscolaires_heuresabsences1_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoriquesAbs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Heuredebut", models.TimeField()),
                ("heurefin", models.TimeField()),
                (
                    "Anneescolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.anneescolaires",
                    ),
                ),
                (
                    "Cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.matieres",
                    ),
                ),
                (
                    "Decoupage",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.decoupages",
                    ),
                ),
                (
                    "Etudiant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.etudiants",
                    ),
                ),
            ],
        ),
    ]
