# Generated by Django 4.1.7 on 2023-06-28 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0028_historiquesabs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historiquesabs",
            old_name="heurefin",
            new_name="Heurefin",
        ),
    ]
