# Generated by Django 4.1.7 on 2023-06-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0030_alter_historiquesabs_etudiant"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacturgences",
            name="Contact",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="contacturgences",
            name="Email",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="contacturgences",
            name="Telephone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
