# Generated by Django 4.1.7 on 2023-07-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "administrations",
            "0031_contacturgences_contact_contacturgences_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historiquesabs",
            name="Datecours",
            field=models.DateField(null=True),
        ),
    ]
