# Generated by Django 4.1.7 on 2023-07-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0032_historiquesabs_datecours"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Aviss", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Postes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Poste", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Service", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Personnels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Matricule", models.CharField(max_length=10, null=True, unique=True)),
                ("Nom", models.CharField(max_length=100)),
                ("Prenoms", models.CharField(max_length=250)),
                ("Datenaissance", models.DateField(null=True)),
                ("Lieunaissance", models.CharField(max_length=15, null=True)),
                ("Telephone", models.CharField(max_length=15, null=True)),
                ("Contact", models.CharField(max_length=15, null=True)),
                ("Email", models.CharField(max_length=50, null=True)),
                (
                    "Photo",
                    models.ImageField(null=True, upload_to="Images/Photos/personnels"),
                ),
                (
                    "Poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.postes",
                    ),
                ),
                (
                    "Service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.services",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Missions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Lieumission", models.CharField(max_length=250, null=True)),
                ("Mission", models.CharField(max_length=1000, null=True)),
                ("Datedebut", models.DateField(null=True)),
                ("Datefin", models.DateField(null=True)),
                ("Delegation", models.CharField(max_length=1000, null=True)),
                ("Moyen", models.CharField(max_length=250, null=True)),
                ("Datemission", models.DateField(null=True)),
                (
                    "Aviss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.avis",
                    ),
                ),
                (
                    "Personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.personnels",
                    ),
                ),
                (
                    "Poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.postes",
                    ),
                ),
                (
                    "Service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.services",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Autorisationspersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Contact", models.CharField(max_length=15, null=True)),
                (
                    "Periode",
                    models.DecimalField(decimal_places=1, max_digits=4, null=True),
                ),
                ("Datedebut", models.DateField(null=True)),
                ("Heuredebut", models.TimeField()),
                ("Datefin", models.DateField(null=True)),
                ("Heurefin", models.TimeField()),
                ("Motif", models.CharField(max_length=1000, null=True)),
                ("Datereprise", models.DateField(null=True)),
                ("Heurereprise", models.TimeField()),
                ("Remplacant", models.CharField(max_length=250, null=True)),
                ("Contactremplacant", models.CharField(max_length=15, null=True)),
                (
                    "Aviss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.avis",
                    ),
                ),
                (
                    "Personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.personnels",
                    ),
                ),
                (
                    "Poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.postes",
                    ),
                ),
                (
                    "Service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.services",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Autorisationsenseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Contact", models.CharField(max_length=15, null=True)),
                (
                    "Periode",
                    models.DecimalField(decimal_places=1, max_digits=4, null=True),
                ),
                ("Datedebut", models.DateField(null=True)),
                ("Heuredebut", models.TimeField()),
                ("Datefin", models.DateField(null=True)),
                ("Heurefin", models.TimeField()),
                ("Motif", models.CharField(max_length=1000, null=True)),
                ("Datereprise", models.DateField(null=True)),
                ("Heurereprise", models.TimeField()),
                ("Remplacant", models.CharField(max_length=250, null=True)),
                ("Contactremplacant", models.CharField(max_length=15, null=True)),
                (
                    "Aviss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.avis",
                    ),
                ),
                (
                    "Enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.enseignants",
                    ),
                ),
                (
                    "Poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.postes",
                    ),
                ),
                (
                    "Service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.services",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Autorisationsauditeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Contact", models.CharField(max_length=15, null=True)),
                (
                    "Periode",
                    models.DecimalField(decimal_places=1, max_digits=4, null=True),
                ),
                ("Datedebut", models.DateField(null=True)),
                ("Heuredebut", models.TimeField()),
                ("Datefin", models.DateField(null=True)),
                ("Heurefin", models.TimeField()),
                ("Motif", models.CharField(max_length=1000, null=True)),
                ("Datereprise", models.DateField(null=True)),
                ("Heurereprise", models.TimeField()),
                ("Remplacant", models.CharField(max_length=250, null=True)),
                ("Contactremplacant", models.CharField(max_length=15, null=True)),
                (
                    "Aviss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.avis",
                    ),
                ),
                (
                    "Etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.etudiants",
                    ),
                ),
                (
                    "Poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.postes",
                    ),
                ),
                (
                    "Service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.services",
                    ),
                ),
            ],
        ),
    ]
