# Generated by Django 4.1.7 on 2023-07-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0035_personnels_statut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autorisationsauditeur",
            name="Poste",
        ),
        migrations.RemoveField(
            model_name="autorisationsauditeur",
            name="Service",
        ),
        migrations.RemoveField(
            model_name="autorisationsenseignant",
            name="Poste",
        ),
        migrations.RemoveField(
            model_name="autorisationsenseignant",
            name="Service",
        ),
        migrations.AddField(
            model_name="autorisationsauditeur",
            name="Salle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.salles",
            ),
        ),
        migrations.AddField(
            model_name="autorisationsenseignant",
            name="Ecole",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.ecoles",
            ),
        ),
    ]
