# Generated by Django 4.1.7 on 2023-07-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0037_dossierscolaires_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Anneescolaire",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.anneescolaires",
            ),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Contact",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Ecole",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Etudiant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dossiers_scolaires",
                to="administrations.etudiants",
            ),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="HeuresabsenceS1",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="HeuresabsenceS2",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Lieunaissance",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Matricule",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Matrimoniale",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Photo",
            field=models.ImageField(blank=True, null=True, upload_to="Images/Photos"),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Prenoms",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Sexe",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name="DossierFinances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Montantscolarité",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "Montantversé",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "Montantrestant",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                ("Matricule", models.CharField(max_length=50, null=True)),
                ("Nom", models.CharField(max_length=100, null=True)),
                ("Ecole", models.CharField(max_length=100, null=True)),
                ("Sexe", models.CharField(max_length=10, null=True)),
                (
                    "Anneescolaire",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.anneescolaires",
                    ),
                ),
                (
                    "Etudiant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossiers_finances",
                        to="administrations.etudiants",
                    ),
                ),
                (
                    "Niveau",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.niveaux",
                    ),
                ),
                (
                    "Salle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.salles",
                    ),
                ),
            ],
        ),
    ]
