# Generated by Django 4.1.7 on 2023-07-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0038_alter_dossierscolaires_anneescolaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossierscolaires",
            name="HeuresabsenceS1",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="HeuresabsenceS2",
            field=models.IntegerField(default=0),
        ),
    ]
