# Generated by Django 4.1.7 on 2023-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0039_alter_dossierscolaires_heuresabsences1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossierfinances",
            name="Montantrestant",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="dossierfinances",
            name="Montantscolarité",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="dossierfinances",
            name="Montantversé",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
