# Generated by Django 4.1.7 on 2023-07-07 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0041_historiquesvers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historiquesvers",
            old_name="Montantscolarité",
            new_name="Montantscolarite",
        ),
        migrations.RenameField(
            model_name="historiquesvers",
            old_name="Montantversé",
            new_name="Montantverse",
        ),
    ]
