# Generated by Django 4.1.7 on 2023-07-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "administrations",
            "0043_rename_montantscolarite_historiquesvers_montantscolarit_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogues",
            name="Prix",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="dossierfinances",
            name="Montantrestant",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="dossierfinances",
            name="Montantscolarité",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="dossierfinances",
            name="Montantversé",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="historiquesvers",
            name="Montantrestant",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="historiquesvers",
            name="Montantscolarit",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="historiquesvers",
            name="Montantvers",
            field=models.IntegerField(null=True),
        ),
    ]
