# Generated by Django 4.1.7 on 2023-07-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0044_alter_catalogues_prix_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossierfinances",
            name="Ecole",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.ecoles",
            ),
        ),
        migrations.AlterField(
            model_name="dossierfinances",
            name="Sexe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.genres",
            ),
        ),
        migrations.AlterField(
            model_name="historiquesvers",
            name="Ecole",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.ecoles",
            ),
        ),
        migrations.AlterField(
            model_name="historiquesvers",
            name="Sexe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.genres",
            ),
        ),
    ]
