# Generated by Django 4.1.7 on 2023-07-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0045_alter_dossierfinances_ecole_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Ecole",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.ecoles",
            ),
        ),
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Sexe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.genres",
            ),
        ),
    ]
