# Generated by Django 4.1.7 on 2023-07-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0046_alter_dossierscolaires_ecole_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossierscolaires",
            name="Matrimoniale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.matrimoniales",
            ),
        ),
    ]
