# Generated by Django 4.1.7 on 2023-07-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "administrations",
            "0048_rename_montantscolarité_dossierfinances_montantscolarit_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("sujet", models.CharField(max_length=100)),
                ("contenu", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "Etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.etudiants",
                    ),
                ),
                (
                    "Salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrations.salles",
                    ),
                ),
            ],
        ),
    ]
