# Generated by Django 4.1.7 on 2023-07-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0050_messagess"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagess",
            name="Salle",
        ),
        migrations.AddField(
            model_name="messagess",
            name="Ecole",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.ecoles",
            ),
        ),
        migrations.AlterField(
            model_name="messagess",
            name="Enseignant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrations.enseignants",
            ),
        ),
        migrations.AlterField(
            model_name="messagess",
            name="nom",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="messagess",
            name="sujet",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
