# Generated by Django 4.1.7 on 2023-07-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrations", "0051_remove_messagess_salle_messagess_ecole_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_code", models.CharField(max_length=100)),
                ("activation_date", models.DateField()),
                ("expiration_date", models.DateField()),
            ],
        ),
    ]
